### ISSUE TITLE
feature request: align floating window vertically when context window is visible

### ISSUE THREAD

**Issue by bassamsdata** [RaafatTurki/corn.nvim#5]
thank you for this awesome plugin—it's a lifesaver for sorting out diagnostics.

quick request: any chance we could make the floating window align below (vertically) the [treesitter-context](https://github.com/nvim-treesitter/nvim-treesitter-context) plugin only when the context window is up? check out the pic for what i mean.

thanks a bunch! 😊

<img width="832" alt="Screenshot 2023-12-04 at 2 24 56 PM" src="https://github.com/RaafatTurki/corn.nvim/assets/105807570/10063164-3520-4bb2-8ade-31ca40e2089d">

**Comment by RaafatTurki** [comment]
Hi!
Nice catch, this feature requires this [issues fixed](https://github.com/nvim-treesitter/nvim-treesitter-context/issues/242) on nvim-treesitter-context which allows the ability to get the height of the context window. I've commented on that issue and we'll see how it goes.

Also thanks for the kind word.

**Comment by bassamsdata** [comment]
Thank you for your interest in implementing this. However, it's unlikely to be fixed as [treesitter-context](https://github.com/nvim-treesitter/nvim-treesitter-context) plugin maintainers won't add an API for this feature. Closing this issue.

Side note: I really appreciate the last feature you added to not cover errors on top of the buffer. Thank you again.
