### ISSUE TITLE
Feature request: don't show diagnostics in insert mode

### ISSUE THREAD

**Issue by TomDeneire** [RaafatTurki/corn.nvim#7]
Hi there,

congrats on the plugin! I tried something similar ago (so I know it's not an easy feat), https://github.com/TomDeneire/notify-diagnostics.nvim, but I didn't quite get the solution I wanted. So I really like your plugin, but one thing that (for me) could improve the functionality is not having LSP diagnostics while in insert mode, which I find distracting.

All the best,

Tom.

**Comment by RaafatTurki** [comment]
Hey
Thanks for the feedback!
I've just pushed a new update, you can now add `blacklisted_modes = { 'i' }` in the setup config

**Comment by TomDeneire** [comment]
Super, works like charm!
